apiVersion: v1
kind: Service
metadata:
  name: cie-db
spec:
  ports:
  - port: 3306
  selector:
    app: cie-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cie-db
spec:
  selector:
    matchLabels:
      app: cie-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cie-db
    spec:
      containers:
      - image: mysql/mysql-server:8.0
        name: cie-db
        env:
        - name: MYSQL_DATABASE
          value: cie
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: appuser
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 3306
          name: cie-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: initdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
data:
  initdb.sql: |-
    CREATE USER 'appuser'@'%' IDENTIFIED BY 'appuser';