version: '3.2'
services:
  cie_api:
    container_name: cie-api
    image: vengelmann/docker-repo:cie-api
    # tells Compose where to look for a Dockerfile to build the image 
    # for the service.
    build:
      context: ./api
      dockerfile: Dockerfile
    # tells the container to keep running even when there’s no daemon 
    # specified via CMD in the Dockerfile. Otherwise, it’ll shut down 
    # right after provisioning 
    tty: true
    expose:
      - 5000
    # defines where to put the server-side code in the container / Volumes 
    # are a storage mechanism within containers.
    # volumes:
    #   - './api/:/home/cieuser'
    depends_on:
      - cie-db
  
  cie-db:
    container_name: cie-db
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "cie"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "appuser"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./api/database/:/docker-entrypoint-initdb.d
      # - /var/lib/mysql:/var/lib/mysql
  
  mongo:
    # image: vengelmann/docker-repo:mongo-with-replica
    build: 
      context: ../Rocket.Chat
      dockerfile: Dockerfile-mongo
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"
    ports:
      - "27017:27017"

  rocketchat:
    # image: vengelmann/docker-repo:rocketchat-custom
    build: ../Rocket.Chat/Dockerfile
    # command: 'sleep 99999'
    depends_on: 
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  web:
    container_name: cie_web
    # image: vengelmann/docker-repo:cie_web
    build: ./frontend/Dockerfile
    tty: true
    ports:
      - 8080:80
    depends_on:
      - cie_api
    # makes sure the loadbalancer service doesn’t start unless the backend services 
    # have started. Allows linked services to be used as 
    # references within loadbalancer, which is used in nginx.conf
    links:
      - cie_api

volumes:
  backend:
  db-data: