apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"strapi-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":1337}],"selector":{"app":"strapi"}}}
  creationTimestamp: "2021-06-28T16:27:33Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-06-28T16:27:33Z"
  name: strapi-service
  namespace: default
  resourceVersion: "39143519"
  selfLink: /api/v1/namespaces/default/services/strapi-service
  uid: 9df5a5bb-ea59-4a0d-8d2a-a491d91db0d1
spec:
  clusterIP: 10.245.252.199
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: strapi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
