apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: strapi
  sessionAffinity: None
  type: ClusterIP