# Service for Tomcat server @ 8080
apiVersion: v1
kind: Service
metadata:
  name: cie-guac
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.45
  selector:
    app: cie-guac
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
# Service for Tomcat server @ 8080
apiVersion: "v1"
kind: "Service"
metadata:
  name: "cie-guac"
spec:
  selector:
    app: "cie-guac"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
---
# Guacamole Tomcat server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cie-guac
  labels:
    app: cie-guac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cie-guac
  template:
    metadata:
      labels:
        app: cie-guac
    spec:
      containers:
      - image:  vengelmann/guac-openid
        name: cie-guac
        env:
        - name: GUACD_HOSTNAME
          value: "cie-guacd"
        - name: GUACD_PORT
          value: "4822"
        - name: GUACAMOLE_HOME
          value: "/guac-home"
        ports:
        - containerPort: 8080
          name: cie-guac
---
# This is to access the guacd component
apiVersion: v1
kind: Service
metadata:
  name: "cie-guacd"
spec:
  selector:
    app: "cie-guacd"
  ports:
    - protocol: TCP
      port: 4822
      targetPort: 4822
---
# guacd Component deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cie-guacd"
  labels:
    app: "cie-guacd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cie-guacd"
  template:
    metadata:
      labels:
        app: "cie-guacd"
    spec:
      containers:
      - name: "cie-guacd"
        image: guacamole/guacd
        ports:
          - containerPort: 4822