apiVersion: v1
kind: Service
metadata:
  name: cie-db-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cie-db
spec:
  selector:
    matchLabels:
      app: cie-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cie-db
    spec:
      containers:
      - image: mysql/mysqk-server:8.0
        name: cie-db
        env:
        - name: MYSQL_DATABASE
          value: cie
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: appuser
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
